# Gradle daemon
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Kotlin
kotlin.code.style=official

# AndroidX
android.useAndroidX=true

# Compose
android.enableJetifier=false

# Suppress AGP 8.4 + compileSdk 35 compatibility warning
android.suppressUnsupportedCompileSdk=35
